_prefs: 
  mapid: ryanjhodge.4c6f39a2
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: National Park Service
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -124.07
  - 46.0661
  - 10
description: Lewis and Clark National Historic Park Vegeation Inventory Map
format: "png8:m=h"
interactivity_layer: lewi_vegetation
layers: null
maxzoom: 22
minzoom: 0
name: LEWI Vegetation Inventory Map
source: "mapbox:///ryanjhodge.ecdda60d"
styles: 
  - style.mss
template: "<b>Vegetation Map Unit:</b> {{mapunit_name}}"
